version: '3.9'

networks:
    laravel:

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.dockerfile
        container_name: webserver
        ports:
            - 8082:80
        volumes:
            - ./:/var/www/html/
        links:
            - fpm
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: docker/fpm.dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        links:
            - db
        networks:
            - laravel

    # supervisor:
    #     image: app
    #     networks:
    #         - laravel
    #     depends_on:
    #         - fpm
    #         - nginx
    #     command: supervisord
    #     volumes:
    #       - ./docker/general/supervisord.conf:/etc/supervisord.conf

    # supervisor:
    #   container_name: supervisor
    #   image: redditsaved/laravel-supervisord:latest
    #   restart: unless-stopped
    #   environment:
    #     - APP_ROOT=${APP_ROOT}
    #     - QUEUE_DRIVER=${QUEUE_CONNECTION}
    #     - OPTIONS=${QUEUE_OPTIONS}
    #     - NUM_PROCS=${NUM_PROCS}
    #   volumes:
    #     - laravel_directory:${APP_ROOT}
    #     - ./docker/general/supervisord.conf:/etc/supervisord.conf
    #   network_mode: host

    #db
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=fisat
            - MYSQL_PASSWORD=fisat@2022
            - MYSQL_DATABASE=fisat
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/config/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        links:
            - db
        ports:
            - "8081:80"
        networks:
            - laravel

#Volumes
volumes:
    dbdata:
        driver: local
    laravel_directory:
        driver: local
